sudo: required
services:
  - docker

before_install:
  - docker build -t marivaldosena/dockfront -f Dockerfile.dev .

script:
  - docker run marivaldosena/dockfront npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "dockfront"
  env: "msena-dockfront"
  bucket_name: "elasticbeanstalk-us-east-2-128350299167"
  bucket_path: "dockfront"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY